### ISSUE TITLE
The governance qps provider control provider global dynamic config

### ISSUE THREAD

**Issue by jeho0815** [ServiceComb/java-chassis#21]
Hi, the qps provider control now must choose a microservice name, so it dosn't support global qps dynamic config.
`private void initConfig(String key) {
        if (watchedKeySet.contains(key)) {
            return;
        }
        watchedKeySet.add(key);
        String configKey = Config.PROVIDER_LIMIT_KEY_PREFIX + key;
        DynamicProperty property = DynamicProperty.getInstance(configKey);
        initQpsLimit(key, getIntegerLimitProperty(property));
        property.addCallback(() -> {
            updateQpsLimit(key, getIntegerLimitProperty(property));
            QpsController qpsController = findReference(key);
            objMap.put(key, qpsController);
        });
    }`
configKey contains the key.

**Comment by WillemJiang** [comment]
Do you mind create a PR for it ?

**Comment by liubao68** [comment]
https://github.com/ServiceComb/java-chassis/pull/54
